### ISSUE TITLE
Illegal Memory access error

### ISSUE THREAD

**Issue by ag1988** [ptillet/torch-blocksparse#15]
Hi, sometimes I get an error if someone else is also using the same GPU. Can you check if the following code runs fine for you?

import torch
import torch_blocksparse

Z, H, M, N, K = 100, 2, 1, 2048, 512
a = torch.rand((Z, H, M, K), dtype=torch.float32).cuda()
b = torch.rand((H, K, N), dtype=torch.float32).cuda()
block = 16
layout = torch.ones(H, K//block, N//block).long()
dot = torch_blocksparse.MatMul(layout, block, 'dds', trans_a=False, trans_b=False)
c = dot(a, b)
print(c.shape)

![image](https://user-images.githubusercontent.com/34059288/87247269-7c051f80-c45b-11ea-8d59-41fbe2d4239e.png)

**Comment by ptillet** [comment]
That's pretty interesting. At this moment I have no clue why this would be the case, but I'll look into that some more when I get some time :)

**Comment by ptillet** [comment]
I fixed some undefined behavior in the way Triton handled work from CUDA contexts created by pytorch (https://github.com/ptillet/triton/commit/7710e048f457c46afb1d222afdb5eac35a51e035). I have no way to test whether or not it solved the problem, but I feel like it should have resolved the issue. Feel free to re-open it if it persists.
